# Inspired by https://github.com/marketplace/actions/setup-perl-environment
name: Testing

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: '0 0 * * 1'

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ 'ubuntu-latest', 'macos-latest' ]
        # we are not testing with 5.10 because it exits with different exit code on failure and mess test data. We can handle that with engine, but good enough for now.
        perl: [ '5.36.0', '5.34.1', '5.32.1', '5.30.3', '5.28.3', '5.26.3', '5.24.4', '5.22.4', '5.20.3', '5.18.4', '5.16.3', '5.14.4', '5.12.5' ]
    name: Perl ${{ matrix.perl }} on ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up perl
        uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: ${{ matrix.perl }}
          install-modules-with: cpanm
          install-modules-args: --nocache
      - name: Testing
        run: |
          cpanm --installdeps .
          prove -lv t

